### ISSUE TITLE
post-receive hook and jekyll-plugins

### ISSUE THREAD

**Issue by aliirz** [recurser/jekyll-plugins#13]
I am having some issues when i deploy my website via a post-receive hook to my linode server. I am using the generate_sitemap.rb and generate_categories.rb plugins. when i generate my website on local machine it all works fine. but when i deploy the website, the sitemap.xml does not get generated and neither do the categories work. help please..

**Comment by gokceneraslan** [comment]
Same here. Any help?

**Comment by aliirz** [comment]
@gokceneraslan  nopes :( I am still facing the same problem

**Comment by recurser** [comment]
Apologies for the (huge) delay here. This project is no longer maintained, and I'm archiving it.
