### ISSUE TITLE
Generate_Project.rb not working (here)

### ISSUE THREAD

**Issue by arguser** [recurser/jekyll-plugins#14]
I have the plugin and required gems, starting _jekyll_ I get **no errors** and the message which tells you the project is being cloned ( I've checked on /tmp and it's there) but when I look into the site folder there's no _projects_ folder or anything alike.

what should I check to make it work properly?

**Comment by cyberflow** [comment]
I have same problems. Please help.

**Comment by hammackj** [comment]
Same issue here. Doesn't work at all. The site is fairly blank. Getting these after it does the git co part:

```
+---------------------------------------------------------------------------
!/home/hammackj/.rvm/gems/ruby-1.9.2-p320/gems/maruku-0.6.0/lib/maruku/errors_management.rb:49:in `maruku_error'
!/home/hammackj/.rvm/gems/ruby-1.9.2-p320/gems/maruku-0.6.0/lib/maruku/output/to_html.rb:716:in `to_html_link'
!/home/hammackj/.rvm/gems/ruby-1.9.2-p320/gems/maruku-0.6.0/lib/maruku/output/to_html.rb:970:in `block in array_to_html'
!/home/hammackj/.rvm/gems/ruby-1.9.2-p320/gems/maruku-0.6.0/lib/maruku/output/to_html.rb:961:in `each'
!/home/hammackj/.rvm/gems/ruby-1.9.2-p320/gems/maruku-0.6.0/lib/maruku/output/to_html.rb:961:in `array_to_html'
\___________________________________________________________________________
Not creating a link for ref_id = "at".

```

**Comment by peri4n** [comment]
Same problem here.

**Comment by recurser** [comment]
Apologies for the (huge) delay here. This project is no longer maintained, and I'm archiving it.
