### ISSUE TITLE
Question: Category List

### ISSUE THREAD

**Issue by arguser** [recurser/jekyll-plugins#17]
Hello, I would like to know which would be the proper way to generate a _Category List_ index with all the categories of the site.

Thanks :)

**Comment by odraccir** [comment]
+1
adding some example could be really helpful...

**Comment by recurser** [comment]
Sorry for the slow reply - the plugin only supports generating a page for each category unfortunately... it doesn't support generating a page listing all of the categories. I haven't tried myself, but I wouldn't think it would be too hard to make a custom page - _site.categories_ provides the list, so a plugin seems like it would be overkill for this.
