### ISSUE TITLE
Sitemap generator not picking up `/tag/` directory pages

### ISSUE THREAD

**Issue by edhedges** [recurser/jekyll-plugins#21]
I am not sure why because in the documentation it says it loops through the entire jekyll `_site` directory and creates the site map from pages in there.

Any ideas? I am using [jekyll-tagging](https://github.com/pattex/jekyll-tagging).

**Comment by recurser** [comment]
Apologies for the (huge) delay here. This project is no longer maintained, and I'm archiving it.
