### ISSUE TITLE
Categories regexp.

### ISSUE THREAD

**Issue by afterdesign** [recurser/jekyll-plugins#25]
If you're going to add 2 categories like "C++" and "C#" this plugin is going to work incorrectly.
Now there is regexp:

``` ruby
category = category.gsub(/_|\P{Word}/, '-').gsub(/-{2,}/, '-').downcase
```

Both categories are going to generate "c-" as category name and the file with category will be overwritten.

I think this should be something like (and it's working for me):

``` ruby
category = URI::encode(category).downcase
```

**Comment by recurser** [comment]
Good point @afterdesign - I hadn't considered this. I'm hesitant to change the defaults since it will break existing links, but I'll look into adding this as a non-default option.

**Comment by claman** [comment]
Not sure if this is related or not, but when I try to use the categories plugin I get these two errors: 

```
/Library/Ruby/Gems/1.8/gems/liquid-2.5.2/lib/liquid/i18n.rb:27: warning: regexp has invalid interval
/Library/Ruby/Gems/1.8/gems/liquid-2.5.2/lib/liquid/i18n.rb:27: warning: regexp has `}' without escape
```

**Comment by recurser** [comment]
Apologies for the (huge) delay here. This project is no longer maintained, and I'm archiving it.
