### ISSUE TITLE
content is not render by using markdown

### ISSUE THREAD

**Issue by teddychan** [recurser/jekyll-plugins#27]
I installed this plugin, but found that the generated category page do not render the post content correctly.

my post file is a markdown, is there any idea how to enable this function?

**Comment by HonestSausage** [comment]
Yes I get the same issue as this, when I use {{ post.content }} it displays but in raw markdown.

**Comment by teddychan** [comment]
only the index and original post page is rendered.

all other plugin page, such as category, is not rendered.

**Comment by dhhdev** [comment]
Haven't tried to use this plugin myself. But have you remembered to set a "render?"

_config.yml (Mine looks like this.)

```
# Dependencies
markdown:      rdiscount
pygments:      true

# Pagination
paginate: 5
paginate_path: /blog/page:num

# Permalinks
permalink:     /blog/:categories/post/:year/:month/:day/:title

# Server
dev_env:       true
name:          "example.com"
url:           http://www.example.com
destination:   ./_site
port:          9001
```

I just think the problem might be, that it relies on it being set. (markdown setting)

**Comment by HonestSausage** [comment]
Hi dhh-hss

Thanks for the suggestion. 

I have markdown setting in _config.yml as markdown: redcarpet

I have tried markdown: rdiscount as well as markdown: maruku but get the same error.  In the tag page it displays the post.content as raw markdown and not formatted.

**Comment by dhhdev** [comment]
So it will display the post correctly, just not formatted by the markdown code I assume.
A fix to this, would (or rather, could) be to add "forced markdown."

Like so.

```
{{ page.content | markdownify }}
```

I assume this would work well in this case.
http://jekyllrb.com/docs/templates/

Edit: "Convert a Markdown-formatted string into HTML." (Taken from the page. Just wanted to add this quickly, so you would understand what it does.)

**Comment by HonestSausage** [comment]
Yes that is correct, for the post content it was displaying as the markdown.

Using code {{ post.content | markdownify }} has fixed the issue for me.  

Thanks!

**Comment by dhhdev** [comment]
Glad I could help you Bryan!

**Comment by teddychan** [comment]
yes, confirm it help +1

**Comment by nckrse** [comment]
+1 for markdownify

thank you
