### ISSUE TITLE
Issue building a link of to category posts

### ISSUE THREAD

**Issue by knd** [recurser/jekyll-plugins#30]
I use your script **generate_categories.rb** but it seems I'm having this trouble:

On local: 
I successfully build and navigate to `localhost:4000/categories/programming`  which renders **category_index.html** and `programming` is my category in this case. Seems good so far.

However, on remote after build:
The link `http://mysite.github.io/categories/programming` redirects to not found 404 page. This troubles me and I'm looking for a way to debug or configure this. Any advice? Thank you.

**Comment by raphaelfabeni** [comment]
I'm on this same problem! =/

**Comment by finalfish** [comment]
me too...

**Comment by recurser** [comment]
Apologies for the (huge) delay here. This project is no longer maintained, and I'm archiving it.
