### ISSUE TITLE
Anyway to tweak the category plugin to include pages?

### ISSUE THREAD

**Issue by tomjoht** [recurser/jekyll-plugins#33]
The category plugin works great for posts, but how about pages? I'm using Jekyll as a knowledgebase, using categories (tags actually) with pages. I was trying to find a way to auto-generate tag archives for pages. Could this category plugin somehow be adjusted to include pages?

**Comment by recurser** [comment]
Apologies for the (huge) delay here. This project is no longer maintained, and I'm archiving it.
